server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_db
    username: portfolio
    password: portfolio123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true

jwt:
  secret: portfolioMakerSecretKey123456789portfolioMakerSecretKey123456789
  expiration: 86400000